export const ADD_PLAYER = 'ADD_PLAYER';
export const START_GAME = 'START_GAME';
export const SELECT_MISSION = 'SELECT_MISSION';
export const RECORD_VOTE = 'RECORD_VOTE';
export const START_MISSION = 'START_MISSION';
export const RECORD_MISSION_ACTION = 'RECORD_MISSION_ACTION';
export const NEXT_PLAYER = 'NEXT_PLAYER';
export const RECORD_ASSASSIN_ACTION = 'RECORD_ASSASSIN_ACTION';